{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ror-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ror-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ror-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
{{- end }}
